import type { Metadata } from "next";
import { Source_Serif_4, Instrument_Serif, Old_Standard_TT } from "next/font/google";
import "./globals.css"

const source = Source_Serif_4({
    variable: "--font-source-sans",
    subsets: ["latin"],
})

const instrument = Instrument_Serif({
  subsets: ["latin"],
  weight: "400",
})

const old_standard = Old_Standard_TT({
  weight: "400",
  subsets: ["latin"],
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <body className={`${old_standard.className} antialiased tracking-tight`}>
        <div className="min-h-screen flex flex-col justify-between pt-0 md:pt-8 p-2 dark:bg-zinc-950 bg-white text-gray-900 dark:text-zinc-200">
          <main className="max-w-[90ch] mx-auto w-full space-y-6">
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  )
}

function Footer() {
  const links = [
    { name: 'github', url: 'https://github.com/WUNISTUDIOS' },
    { name: '@trouwsers', url: 'https://www.instagram.com/trouwsers/' }
  ];

  return (
    <footer className="mt-12 text-center">
      <div className="flex justify-center space-x-4 tracking-tight">
        {links.map((link) => (
          <a
            key={link.name}
            href={link.url}
            target="_blank"
            rel="noopener noreferrer"
            className="text-gray-400 dark:text-gray-500 hover:text-blue-500 transition-colors duration-200"
          >
            {link.name}
          </a>
        ))}
      </div>
    </footer>
  );
}
